encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.article, name="article"),
    path("search/", views.search, name="search"),
    path("new/", views.newEntry, name="newEntry"),
    path("edit/<str:title>", views.editEntry, name="editEntry"),
    path("random/", views.randomArticle, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from markdown2 import Markdown
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from django.contrib import messages
import random

from . import util

markdowner = Markdown()

class entryForm(forms.Form):

    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'name':'title'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'name':'body'}))

    def clean_title(self):
        title = self.cleaned_data['title']
        if title.lower() in list(map(lambda x: x.lower(), util.list_entries())):
            raise forms.ValidationError("Article already exists.")
        return title


def index(request):

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def article(request, title):

    if(request.method=="POST"):
        text=request.POST["body"]
        util.save_entry(title, text)
        return HttpResponseRedirect(reverse('encyclopedia:article', args=[title]))

    html = util.get_entry(title)
    if(html is not None):
        html = markdowner.convert(util.get_entry(title))

    return render(request, "encyclopedia/article.html",
    {
        "title": title,
        "text": html
    })

def search(request): 

    title = request.GET["q"]
    if title.lower() in list(map(lambda x: x.lower(), util.list_entries())):
        return HttpResponseRedirect(reverse('encyclopedia:article', args=[title]))
    else:
        results = []
        for x in util.list_entries():
            if x.lower().find(title.lower()) != -1:
                results.append(x)
        
        return render(request, "encyclopedia/search.html", {
            "results": results
        })

def newEntry(request):

    """ if request.method == 'POST':
        newTitle = request.POST['title']
        newBody = request.POST['body']

        if newTitle.lower() not in list(map(lambda x: x.lower(), util.list_entries())):
            util.save_entry(newTitle, newBody)
            return HttpResponseRedirect(reverse('encyclopedia:article', args=[newTitle]))
            
        else:
            return """
    
    if request.method == 'POST':
        form = entryForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            body = form.cleaned_data['body']
            util.save_entry(title, body)
            return HttpResponseRedirect(reverse('encyclopedia:article', args=[title]))
        else:
            return render(request, "encyclopedia/newEntry.html", {
                'form': form
            })

    return render(request, "encyclopedia/newEntry.html",{
        'form': entryForm
    })

def editEntry(request, title):

    text = util.get_entry(title)

    return render(request, "encyclopedia/editEntry.html",
    {
        "title":title,
        "text":text
    })

def randomArticle(request):
    title= random.choice(util.list_entries())

    return article(request, title)

encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}


    {% block title %}
    {{title}}
    {% endblock %}

    {% block body %}
        {% if text != None %}
            <a href="{% url 'encyclopedia:editEntry' title %}" class='edit'>Edit page</a>
            {{text | safe}}
        {% else %}
            Error: Page does not exist.
        {% endif %}
    {% endblock %}

encyclopedia/templates/encyclopedia/editEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit Entry
{% endblock %}

{% block body %}

<h2>Edit Page: </h2>

<form class="editEntry" action="{% url 'encyclopedia:article' title %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="editTitle">Title:</label>
        <input id = 'editTitle' name = 'title' type = 'text' value='{{title}}' disabled>
    </div>
    <textarea name='body'>{{text}}</textarea>
    <input id = 'editSubmit' name='submit' type='submit'>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:article' entry %}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newEntry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Entry
{% endblock %}

{% block body %}

<h2>Create New Page: </h2>

<form class="editEntry" action="{% url 'encyclopedia:newEntry' %}" method="POST">
    {% csrf_token %}
    <div class='formElement'>
        <label for="{{ form.title.id_for_label }}">Title:</label>
        {{form.title}}
    </div>
    {% for error in form.title.errors %}
    <p>{{error}}</p>
    {% endfor %}
    <div class='body'>
        {{form.body}}
    </div>
    <input id = 'editSubmit' name='submit' type='submit' required>
    </div>
    
</form>



<!-- <form class="editEntry" action="{% url 'encyclopedia:newEntry' %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="editTitle">Title:</label>
        <input id = 'editTitle' name = 'title' type = 'text' required>
    </div>
    <textarea name='body'></textarea>
    <input id = 'editSubmit' name='submit' type='submit' required>
</form> -->
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
Search Results
{% endblock %}

{% block body %}

<h2>Search Results: </h2>

    <ul>
        {% for result in results %}
            <li><a href="{% url 'encyclopedia:article' result %}">{{result}}</a></li>
        {% empty %}
            <h6>No results</h6>
        {% endfor %}
    </ul>
{% endblock %}